image: alpine:3.7
build:
  stage: build
  script:
    - pwd
    - ls -al
    - uname -m 
    - apk update && apk add make grub xorriso bash
    - bash build.sh --iso
  artifacts:
    paths:
      - vtos.bin
      - vtos.iso
