image: alpine:3.7
build:
  stage: build
  script:
    - uname -m 
    - apk update && apk add make grub xorriso bash
    - tar -xf i686-elf.tar.gz
    - bash build.sh --iso
  artifacts:
    paths:
      - vtos.bin

